wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.6
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712642122.0
    t:
      1:
      - 1
      - 5
      - 9
      - 50
      - 53
      - 55
      - 77
      - 103
      - 105
      3:
      - 13
      - 15
      - 23
      4: 3.8.19
      5: 0.16.6
      8:
      - 3
      - 8
      13: windows-amd64
